CREATE DATABASE taskmanagerapp;

CREATE TABLE TASKS (
	task_id BIGINT(10) NOT NULL AUTO_INCREMENT,
	parent_task VARCHAR(50) NULL DEFAULT NULL,
	task VARCHAR(50) NULL DEFAULT NULL,
	priority VARCHAR(2) NULL DEFAULT NULL,
	start_date DATE NULL DEFAULT NULL,
	end_date DATE NULL DEFAULT NULL,
	status VARCHAR(10) NULL DEFAULT NULL,
	parent_id BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (task_id),
	CONSTRAINT FK_TASKS FOREIGN KEY (parent_id) REFERENCES TASKS (task_id)
);

CREATE TABLE PARENT_TASK (
    parent_id INT NOT NULL AUTO_INCREMENT,
    parent_task VARCHAR(100) NOT NULL,
    PRIMARY KEY (parent_id)
);